name: Python package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          pip install -e .[dev]
      - name: Codestyle with black and isort
        run: |
          black --config=pyproject.toml --check utilities
          isort --settings-path=pyproject.toml --check utilities
      - name: Lint with pylint
        run: |
          pylint --rcfile=pyproject.toml utilities
      - name: Lint with mypy
        run: |
          python -m pip install types-PyYAML
          mypy --config-file=pyproject.toml utilities
      - name: Test with pytest
        run: |
          pytest . --disable-pytest-warnings
